server:
  port: 8085

management:
  server:
    port: 9091

consumer-group:
  prefix: dev

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abcd@gmail.com
    password: abcd efgh ijkl mnop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 6MB
  jackson:
    default-property-inclusion: NON_NULL
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: sample-service

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: psql
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: true
    show-sql: false
    format-sql: true
    use_sql_comments: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

  cors:
    allowed-origins:
      - "http://localhost:4200"
      - "http://localhost:4201"
    allowed-origins-patterns:
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "OPTIONS"
      - "DELETE"
      - "PATCH"
    allowCredentials: true
    maxAge: 1800

  springdoc:
    swagger-ui:
      url: /v3/api-docs
      operationsSorter: method
      tagsSorter: alpha

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
  enable-native-support: true

application:
  cache:
    ehcache:
      max-entries: 100
      time-to-live-seconds: 3600
  cors:
    allowed-origins:
      - "https://fikre4444.github.io/project-base-setup-ui"
      - "http://localhost:5173"
      - "http://localhost:6004"
      - "http://localhost:4200"
      - "http://localhost:4201"

    allowed-origin-patterns: "https://*.githubpreview.dev"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800

minio:
  endpoint: http://localhost:9000
  access-key: minio-admin
  secret-key: minio-admin
  bucket-name: documents

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-expiration: 604800000
